<a href="https://colab.research.google.com/github/vvrgit/Python/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [5]:
import numpy as np
a=np.array([10,20,30,40,50])
print("a=",a)
print(type(a))

a= [10 20 30 40 50]
<class 'numpy.ndarray'>


In [6]:
import numpy as np
b=np.array((1,2,3,4,5))
print("b=",b)
print(type(a))

b= [1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np
c=np.array(10)
print("c=",c)
print(type(c))

c= 10
<class 'numpy.ndarray'>


In [8]:
import numpy as np
d = np.array([1, 2, 3, 4, 5])
print(d)
print(type(d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [10]:
import numpy as np
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
print(type(e))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [11]:
import numpy as np
f=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("f=",f)
print(type(f))

f= [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [13]:
import numpy as np
a=np.array(2)
b=np.array([2,3])
c=np.array([[2,3],[4,5]])
d=np.array([[[2,3],[4,5]],[[1,2],[3,4]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [15]:
import numpy as np
a=np.array([1,2,3],ndmin=5)
print("a=",a)
print(type(a))

a= [[[[[1 2 3]]]]]
<class 'numpy.ndarray'>


In [18]:
import numpy as np
a=np.array([10,20,30,40])
print("first element:",a[0])
print("second element:",a[1])
print("third element:",a[2])
print("fourth element:",a[3])

first element: 10
second element: 20
third element: 30
fourth element: 40


In [19]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print("First row, third element:",a[0,2])

First row, third element: 30


In [20]:
import numpy as np
a=np.array([[[1,2,3],[2,3,4]],[[3,2,1],[4,3,2]]])
print("Third element of the second array of the first array:",a[0,1,2])

Third element of the second array of the first array: 4


In [21]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [22]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [24]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [25]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [26]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [29]:
import numpy as np
a=np.array([[[1,2,3],[2,3,4]],[[3,2,1],[4,3,2]]])
print("last element of the second array of the first array:",a[0,1,-1])

last element of the second array of the first array: 4
