<a href="https://colab.research.google.com/github/vvrgit/Python/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print("a=",a)
print(type(a))

a= [10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
b=np.array((1,2,3,4,5))
print("b=",b)
print(type(a))

b= [1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
c=np.array(10)
print("c=",c)
print(type(c))

c= 10
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
d = np.array([1, 2, 3, 4, 5])
print(d)
print(type(d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
print(type(e))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
f=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("f=",f)
print(type(f))

f= [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array(2)
b=np.array([2,3])
c=np.array([[2,3],[4,5]])
d=np.array([[[2,3],[4,5]],[[1,2],[3,4]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
a=np.array([1,2,3],ndmin=5)
print("a=",a)
print(type(a))

a= [[[[[1 2 3]]]]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print("first element:",a[0])
print("second element:",a[1])
print("third element:",a[2])
print("fourth element:",a[3])

first element: 10
second element: 20
third element: 30
fourth element: 40


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print("First row, third element:",a[0,2])

First row, third element: 30


In [ ]:
import numpy as np
a=np.array([[[1,2,3],[2,3,4]],[[3,2,1],[4,3,2]]])
print("Third element of the second array of the first array:",a[0,1,2])

Third element of the second array of the first array: 4


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [ ]:
import numpy as np
a=np.array([[[1,2,3],[2,3,4]],[[3,2,1],[4,3,2]]])
print("last element of the second array of the first array:",a[0,1,-1])

last element of the second array of the first array: 4


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[-3:-1])

[30 40]


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[0:4:2])

[10 30]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[0,1:3])

[20 30]


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:3,0])

[40 70]


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:3,0:2])


[[40 50]
 [70 80]]


In [ ]:
import numpy as np
marks=np.array([[101,35,98,43,65,78,96],[102,87,45,98,65,34,78],[103,45,26,78,45,67,34],[104,45,56,67,78,89,90],[105,23,34,45,56,76,87]])
print(marks)
students=marks.shape[0]

[[101  35  98  43  65  78  96]
 [102  87  45  98  65  34  78]
 [103  45  26  78  45  67  34]
 [104  45  56  67  78  89  90]
 [105  23  34  45  56  76  87]]


In [ ]:
Hall_Ticket_No=int(input("enter hall ticket no."))
for i in range(students):
  if(Hall_Ticket_No==marks[i,0]):
    break
print("index=",i)
index=i

enter hall ticket no.105
index= 4


In [ ]:
marks_percentage=np.sum(marks[index,1:marks.shape[1]])*100/600
print(marks_percentage)

53.5


In [ ]:
count=0
failed_sub=[]
for i in range(1,marks.shape[1]):
  if(marks[index,i]<35):
    count=count+1
    failed_sub.append(i)

print(failed_sub)
if(count>0):
  print("Fail")
else:
  print("Pass")


[1, 2]
Fail


# **Lab Assignment Based on Numpy and List**

In [24]:
import numpy as np
marks=np.array([[101,35,98,43,65,78,96],[102,87,45,98,65,34,78],[103,45,26,78,45,67,34],[104,45,56,67,78,89,90],[105,23,34,45,56,76,87]])
students=marks.shape[0]

Hall_Ticket_No=int(input("enter hall ticket no."))
for i in range(students):
  if(Hall_Ticket_No==marks[i,0]):
    break
index=i

marks_percentage=np.sum(marks[index,1:marks.shape[1]])*100/600

count=0
failed_sub=[]
for i in range(1,marks.shape[1]):
  if(marks[index,i]<35):
    count=count+1
    failed_sub.append(i)

print("================================")
print("     KINDERLAND SCHOOL          ")
print("       Score Card               ")
print("================================")
print("Roll No:",Hall_Ticket_No)
print("Telugu:",marks[index,1])
print("English:",marks[index,2])
print("Hindi:",marks[index,3])
print("Maths:",marks[index,4])
print("Science:",marks[index,5])
print("social:",marks[index,6])
print("================================")
print("      Results Status              ")
print("================================")
if(count>0):
  print("Fail")
  print("Failed Subjects:",)
  for i in range(len(failed_sub)):
    if(failed_sub[i]==1):
      print("Telugu")
    if(failed_sub[i]==2):
      print("English")
    if(failed_sub[i]==3):
      print("Hindi")
    if(failed_sub[i]==4):
      print("Maths")
    if(failed_sub[i]==5):
      print("Science")
    if(failed_sub[i]==6):
      print("Social")
else:
  print("Pass")
  print("Percentage of marks:",np.round(marks_percentage))
print("================================")

enter hall ticket no.101
     KINDERLAND SCHOOL          
       Score Card               
Roll No: 101
Telugu: 35
English: 98
Hindi: 43
Maths: 65
Science: 78
social: 96
      Results Status              
Pass
Percentage of marks: 69.0
