<a href="https://colab.research.google.com/github/vvrgit/Python/blob/main/Numpy_Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
print(np.__version__)

1.26.4


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print("a=",a)
print(type(a))

a= [10 20 30 40 50]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
b=np.array((1,2,3,4,5))
print("b=",b)
print(type(a))

b= [1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
c=np.array(10)
print("c=",c)
print(type(c))

c= 10
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
d = np.array([1, 2, 3, 4, 5])
print(d)
print(type(d))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
e=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(e)
print(type(e))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
f=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("f=",f)
print(type(f))

f= [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array(2)
b=np.array([2,3])
c=np.array([[2,3],[4,5]])
d=np.array([[[2,3],[4,5]],[[1,2],[3,4]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
import numpy as np
a=np.array([1,2,3],ndmin=5)
print("a=",a)
print(type(a))

a= [[[[[1 2 3]]]]]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a=np.array([10,20,30,40])
print("first element:",a[0])
print("second element:",a[1])
print("third element:",a[2])
print("fourth element:",a[3])

first element: 10
second element: 20
third element: 30
fourth element: 40


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60]])
print("First row, third element:",a[0,2])

First row, third element: 30


In [ ]:
import numpy as np
a=np.array([[[1,2,3],[2,3,4]],[[3,2,1],[4,3,2]]])
print("Third element of the second array of the first array:",a[0,1,2])

Third element of the second array of the first array: 4


In [ ]:
import numpy as np
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0, 1, 2])

6


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('5th element on 2nd row: ', arr[1, 4])

5th element on 2nd row:  10


In [ ]:
import numpy as np
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[1])

2


In [ ]:
import numpy as np
a=np.array([[[1,2,3],[2,3,4]],[[3,2,1],[4,3,2]]])
print("last element of the second array of the first array:",a[0,1,-1])

last element of the second array of the first array: 4


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[-3:-1])

[30 40]


In [ ]:
import numpy as np
a=np.array([10,20,30,40,50])
print(a[0:4:2])

[10 30]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])

[1 3 5 7]


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[0,1:3])

[20 30]


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:3,0])

[40 70]


In [ ]:
import numpy as np
a=np.array([[10,20,30],[40,50,60],[70,80,90]])
print(a[1:3,0:2])


[[40 50]
 [70 80]]


In [ ]:
import numpy as np
marks=np.array([[101,35,98,43,65,78,96],[102,87,45,98,65,34,78],[103,45,26,78,45,67,34],[104,45,56,67,78,89,90],[105,23,34,45,56,76,87]])
print(marks)
students=marks.shape[0]

[[101  35  98  43  65  78  96]
 [102  87  45  98  65  34  78]
 [103  45  26  78  45  67  34]
 [104  45  56  67  78  89  90]
 [105  23  34  45  56  76  87]]


In [ ]:
Hall_Ticket_No=int(input("enter hall ticket no."))
for i in range(students):
  if(Hall_Ticket_No==marks[i,0]):
    break
print("index=",i)
index=i

enter hall ticket no.105
index= 4


In [ ]:
marks_percentage=np.sum(marks[index,1:marks.shape[1]])*100/600
print(marks_percentage)

53.5


In [ ]:
count=0
failed_sub=[]
for i in range(1,marks.shape[1]):
  if(marks[index,i]<35):
    count=count+1
    failed_sub.append(i)

print(failed_sub)
if(count>0):
  print("Fail")
else:
  print("Pass")


[1, 2]
Fail


# **Lab Assignment Based on Numpy and List**

In [ ]:
import numpy as np
marks=np.array([[101,35,98,43,65,78,96],[102,87,45,98,65,34,78],[103,45,26,78,45,67,34],[104,45,56,67,78,89,90],[105,23,34,45,56,76,87]])
students=marks.shape[0]

Hall_Ticket_No=int(input("enter hall ticket no."))
for i in range(students):
  if(Hall_Ticket_No==marks[i,0]):
    break
index=i

marks_percentage=np.sum(marks[index,1:marks.shape[1]])*100/600

count=0
failed_sub=[]
for i in range(1,marks.shape[1]):
  if(marks[index,i]<35):
    count=count+1
    failed_sub.append(i)

print("================================")
print("     KINDERLAND SCHOOL          ")
print("       Score Card               ")
print("================================")
print("Roll No:",Hall_Ticket_No)
print("Telugu:",marks[index,1])
print("English:",marks[index,2])
print("Hindi:",marks[index,3])
print("Maths:",marks[index,4])
print("Science:",marks[index,5])
print("social:",marks[index,6])
print("================================")
print("      Results Status              ")
print("================================")
if(count>0):
  print("Fail")
  print("Failed Subjects:",)
  for i in range(len(failed_sub)):
    if(failed_sub[i]==1):
      print("Telugu")
    if(failed_sub[i]==2):
      print("English")
    if(failed_sub[i]==3):
      print("Hindi")
    if(failed_sub[i]==4):
      print("Maths")
    if(failed_sub[i]==5):
      print("Science")
    if(failed_sub[i]==6):
      print("Social")
else:
  print("Pass")
  print("Percentage of marks:",np.round(marks_percentage))
print("================================")

enter hall ticket no.101
     KINDERLAND SCHOOL          
       Score Card               
Roll No: 101
Telugu: 35
English: 98
Hindi: 43
Maths: 65
Science: 78
social: 96
      Results Status              
Pass
Percentage of marks: 69.0


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4])
print(a.dtype)

int64


In [ ]:
import numpy as np
b = np.array(['apple', 'banana', 'cherry'])
print(b.dtype)

<U6


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4], dtype='i')
print(a)
print(a.dtype)

[1 2 3 4]
int32


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4], dtype='S')
print(a)
print(a.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 24
print(arr)
print(x)

[24  2  3  4  5]
[24  2  3  4  5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
x[0] = 24
print(arr)
print(x)

[1 2 3 4 5]
[24  2  3  4  5]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
y = arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr.shape)

(2, 4)


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(4, 3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(3,2,2)
print(newarr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.reshape(2, 4).base)

[1 2 3 4 5 6 7 8]


In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
newarr = arr.reshape(2, 2, -1)
print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
newarr = arr.reshape(-1)
print(newarr)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a=np.array([1,2,3,4,5])
for x in a:
  print(x)

1
2
3
4
5


In [ ]:
import numpy as np
b=np.array([[1,2],[4,5]])
for x in b:
  print(x)

[1 2]
[4 5]


In [ ]:
import numpy as np
b=np.array([[[1,2],[4,5]],[[3,4],[5,6]]])
for x in b:
  print(x)

[[1 2]
 [4 5]]
[[3 4]
 [5 6]]


In [ ]:
import numpy as np
b=np.array([[1,2],[4,5]])
for x in b:
  for y in x:
    print(y)

1
2
4
5


In [ ]:
import numpy as np
b=np.array([[[1,2],[4,5]],[[3,4],[5,6]]])
for x in b:
  for y in x:
    for z in y:
      print(z)

1
2
4
5
3
4
5
6


In [ ]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


In [ ]:
import numpy as np

arr = np.array([1, 2, 3])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0,) 1
(1,) 2
(2,) 3


In [ ]:
import numpy as np

arr = np.array([[1, 2],[3,4]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0) 1
(0, 1) 2
(1, 0) 3
(1, 1) 4


In [ ]:
import numpy as np

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

for idx, x in np.ndenumerate(arr):
  print(idx, x)

(0, 0, 0) 1
(0, 0, 1) 2
(0, 1, 0) 3
(0, 1, 1) 4
(1, 0, 0) 5
(1, 0, 1) 6
(1, 1, 0) 7
(1, 1, 1) 8


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.concatenate((a, b))
print(c)

[1 2 3 4 5 6]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c = np.concatenate((a, b),axis=0) #Column
print(c)

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c = np.concatenate((a, b),axis=1) #ROW
print(c)

[[ 1  2 10 20]
 [ 3  4 30 40]]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=0)
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c = np.stack((a, b),axis=0) #Column
print(c)

[[[ 1  2]
  [ 3  4]]

 [[10 20]
  [30 40]]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c = np.stack((a, b),axis=1) #ROW
print(c)

[[[ 1  2]
  [10 20]]

 [[ 3  4]
  [30 40]]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c = np.stack((a, b),axis=0) #Column
print(c)

[[[ 1  2]
  [ 3  4]]

 [[10 20]
  [30 40]]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c = np.hstack((a, b))
print(c)

[[ 1  2 10 20]
 [ 3  4 30 40]]


In [ ]:
import numpy as np
a=np.array([[1,2],[3,4]])
b=np.array([[10,20],[30,40]])
c = np.vstack((a, b))
print(c)

[[ 1  2]
 [ 3  4]
 [10 20]
 [30 40]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 6])
b = np.array_split(a, 3)
print(b[0])
print(b[1])
print(b[2])

[1 2]
[3 4]
[5 6]


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5])
b = np.array_split(a, 4)
print(b[0])
print(b[1])
print(b[2])
print(b[3])

[1 2]
[3]
[4]
[5]


In [ ]:
import numpy as np
a = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])
b = np.array_split(a, 3)
print(b[0])
print(b[1])
print(b[2])

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
b = np.array_split(a, 3)
print(b[0])
print(b[1])
print(b[2])

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18],[19,20,21]])
b = np.array_split(a, 3)
print(b[0])
print(b[1])
print(b[2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]]
[[16 17 18]
 [19 20 21]]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
b = np.array_split(a, 3, axis=1)
print(b[0])
print(b[1])
print(b[2])

[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


# **Thevenin's Theorem**

In [ ]:
vth=float(input("enter thevenin's voltage"))
Rth=float(input("enter thevenin's resistance"))
RL=float(input("enter load resitance"))
IL=vth/(Rth+RL)
PL=(IL**2)*RL
print("current=",IL,"Amps")
print("power=",PL,"Watts")

enter thevenen's voltage100
enter thevenen's resistance200
enter load resitance100
current= 0.3333333333333333 Amps
power= 11.11111111111111 Watts


# ***Norton's Theorem***

In [ ]:
IN=float(input("enter nortons's current"))
Rn=float(input("enter nortons's resistance"))
RL=float(input("enter load resitance"))
IL=IN*Rn/(Rn+RL)1
PL=(IL**2)*RL
print("current=",IL,"Amps")
print("power=",PL,"Watts")

enter nortons's voltage10
enter nortons's resistance200
enter load resitance100
current= 6.666666666666667 Amps
power= 4444.444444444445 Watts


In [ ]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
b = np.array_split(a, 2, axis=1)
print(b[0])
print(b[1])

[[ 1  2]
 [ 4  5]
 [ 7  8]
 [10 11]
 [13 14]
 [16 17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
import numpy as np
a = np.array([[1, 2, 3,4], [4, 5, 6,7], [7, 8, 9,10]])
b = np.hsplit(a, 2)
print(b[0])
print(b[1])

[[1 2]
 [4 5]
 [7 8]]
[[ 3  4]
 [ 6  7]
 [ 9 10]]


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(a == 3)
print(x)

(array([2]),)


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.where(a==6))

(array([1]), array([2]))


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.where(a%2==0))

(array([0, 1, 1, 2]), array([1, 0, 2, 1]))


In [ ]:
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.where(a%2==1))

(array([0, 0, 1, 2, 2]), array([0, 2, 1, 0, 2]))


In [ ]:
import numpy as np

a = np.array([6, 7, 8, 9])

x = np.searchsorted(a, 7)

print(x)

1


In [ ]:
import numpy as np
a = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.searchsorted(a,4)
print(x)

3


In [ ]:
import numpy as np
a=np.array([12,98,34,21])
b=np.sort(a)
print(a)
print(b)

[12 98 34 21]
[12 21 34 98]


In [ ]:
import numpy as np
a = np.array(['banana', 'cherry', 'apple'])
print(np.sort(a))

['apple' 'banana' 'cherry']


In [ ]:
import numpy as np
a = np.array([True, False, True])
print(np.sort(a))

[False  True  True]


In [ ]:
import numpy as np
a = np.array([[3, 2, 4], [5, 0, 1]])
print(np.sort(a))

[[2 3 4]
 [0 1 5]]


In [ ]:
import numpy as np
a = np.array([[[3, 2, 4], [5, 0, 1]],[[30, 20, 40], [50, 0, 10]]])
print(np.sort(a))

[[[ 2  3  4]
  [ 0  1  5]]

 [[20 30 40]
  [ 0 10 50]]]


In [4]:
import numpy as np
marks=np.array([[[101,35,98,43,65,78,96],
                 [102,87,45,98,65,34,78],
                 [103,45,26,78,45,67,34],
                 [104,45,56,67,78,89,90],
                 [105,23,34,45,56,76,87]],
                [[101,53,89,43,56,87,69],
                 [102,78,54,89,56,43,87],
                 [103,54,62,87,54,76,43],
                 [104,35,65,76,87,98,9],
                 [105,32,43,54,65,67,78]]])

stud=marks.shape[1]
sem=marks.shape[0]


Hall_Ticket_No=int(input("enter hall ticket no."))
semester=int(input("enter semester no."))

for i in range(sem):
  if(semester==i+1):
    break
index_sem=i

for j in range(stud):
  if(Hall_Ticket_No==marks[index_sem,j,0]):
    break
index_stud=j
print(index_sem,index_stud)

marks_percentage=np.sum(marks[index_sem,index_stud,1:marks.shape[2]])*100/600

count=0
failed_sub=[]
for i in range(1,marks.shape[2]):
  if(marks[index_sem,index_stud,i]<40):
    count=count+1
    failed_sub.append(i)


print("================================")
print("       SR University            ")
print("       Score Card               ")
print("================================")
print("Roll No:",Hall_Ticket_No)
print("Semester:",semester)
print("Telugu:",marks[index,1])
print("English:",marks[index,2])
print("Hindi:",marks[index,3])
print("Maths:",marks[index,4])
print("Science:",marks[index,5])
print("social:",marks[index,6])
print("================================")
print("      Results Status              ")
print("================================")
if(count>0):
  print("Fail")
  print("Failed Subjects:",)
  for i in range(len(failed_sub)):
    if(failed_sub[i]==1):
      print("Telugu")
    if(failed_sub[i]==2):
      print("English")
    if(failed_sub[i]==3):
      print("Hindi")
    if(failed_sub[i]==4):
      print("Maths")
    if(failed_sub[i]==5):
      print("Science")
    if(failed_sub[i]==6):
      print("Social")
else:
  print("Pass")
  print("Percentage of marks:",np.round(marks_percentage))
print("================================")

enter hall ticket no.101
enter semester no.2
1 0
